name: course-nucmed-myst

channels:
- conda-forge

dependencies:
- mystmd
- imagemagick
- numpy~=1.21 # <2 needed for numeric exercises
- scipy
- matplotlib<=3.8
- jupyter
- parallelproj>=1.10.0
- nibabel
- pymirc
- sympy~=1.10 # needed for numeric exercises
- ipython
